name: Redeemables
version: '${project.version}'
main: dev.sv3ks.redeemables.Redeemables
api-version: 1.21
author: sv3ks
commands:
  redeem:
    description: Redeem a reward by entering a code
  rareload:
    permission: redeemables.reloadcodes
    description: Reloads Redeemables' config